### ISSUE TITLE
vm.nonce is not updated in contract calls.

### ISSUE THREAD

**Issue by ivan-onchain** [theredguild/damn-vulnerable-defi#70]
Based on this issue in the foundry repo looks like the nonce of an address is only updated if that address is used to deploy a contract but not for calling functions

https://github.com/foundry-rs/foundry/discussions/8584

Therefore challenges like `ThePuppet` can't be finished as the player doesn't deploy any contract but the required nonce has to be one.

**Comment by tinchoabbate** [comment]
Thanks for reporting. Yes I'm aware of this behavior, it's being discussed here: https://github.com/theredguild/damn-vulnerable-defi/discussions/57. I don't seem to be able to do anything about it from my side, we've gotta wait for the Foundry folks to fix.

**Comment by CanonicalJP** [comment]
The workaround proposed by Foundry is to use the `--isolated` option to make each tx be executed in a separate EVM context. It look that the option was not working properly either, solved in https://github.com/foundry-rs/foundry/pull/8878

On the other hand, I created https://github.com/theredguild/damn-vulnerable-defi/pull/77 so that the option is included in the Usage section of the README

**Comment by tinchoabbate** [comment]
will include in the next minor release the change in the README. Thanks everyone.
